name: Build Documentation

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5 # Check for the latest stable version
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[docs]
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints sphinx-copybutton

      - name: Build documentation
        run: |
          cd docs/ && sphinx-build -b html source build/html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html

  deploy:
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: docs/build/html

      - name: Set version
        id: set-version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages (Versioned)
        if: steps.set-version.outputs.is_tag == 'true' # Only run for tags
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          destination_dir: ${{ steps.set-version.outputs.version }}
          # user_name: 'github-actions[bot]' # Optional: configure committer username
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: configure committer email
          # commit_message: Deploy ${{ steps.set-version.outputs.version }} to GitHub Pages # Optional: custom commit message

      - name: Deploy to GitHub Pages (Latest)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' # Only run for main/master
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          destination_dir: latest
          # user_name: 'github-actions[bot]' # Optional: configure committer username
          # user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: configure committer email
          # commit_message: Deploy latest to GitHub Pages # Optional: custom commit message
